---
title: "Fiona"
author: "Fiona Miller"
date: "April 10, 2017"
output: html_document
---

```{r setup, include=FALSE}
library(mdsr)
library(tidyverse)
library(RMySQL)
db <- dbConnect_scidb(dbname = "imdb")
```

## Total Films
```{r pressure}
table2 <- db %>%
  dbGetQuery("SELECT mi.movie_id, t.production_year 
FROM movie_info mi
INNER JOIN title t ON t.id = mi.movie_id
WHERE mi.info_type_id = 3  AND t.kind_id = 1;") 
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
table3 <- table2%>%
  group_by(production_year) %>%
  summarise(num_films = sum(n()))
```

```{r}
table4 <- table3 %>%
  mutate(total=sum(num_films))
```


```{r}
table5 <- table4%>%
  mutate(percentage=num_films/total*100)
```

## Total Genres

```{r}
t2 <- db %>%
  dbGetQuery("SELECT mi.movie_id, mi.info, t.production_year 
FROM movie_info mi
INNER JOIN title t ON t.id = mi.movie_id
WHERE mi.info_type_id = 3  AND t.kind_id = 1;") 
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
t3 <- t2%>%
  group_by(production_year) %>%
  summarise(num_films = sum(n()))
```

```{r}
t4 <- t3 %>%
  mutate(total=sum(num_films))
```


```{r}
t5 <- t4%>%
  mutate(percentage=num_films/total*100)